@startuml
actor User
participant Client
participant Admin
participant Account
participant CreditCard

User -> Client: Создание клиента
User -> Account: Создание счета
User -> CreditCard: Создание кредитной карты

User -> Client: Добавление счета к клиенту
Client -> Account: Привязка счета

User -> Client: Добавление кредитной карты к клиенту
Client -> CreditCard: Привязка карты

User -> Client: Оплатить заказ
Client -> Account: Списание средств

User -> Client: Перевести средства
Client -> Account: Списание средств
Account -> Account: Зачисление средств

User -> Client: Заблокировать кредитную карту
Client -> CreditCard: Блокировка карты

User -> Admin: Проверка кредитного лимита
Admin -> CreditCard: Проверить превышение лимита
Admin -> CreditCard: Заблокировать карту, если превышен лимит

User -> Client: Аннулировать счет
Client -> Account: Закрытие счета

@enduml